### ISSUE TITLE
Форма ввода задачи

### ISSUE THREAD

**Issue by PavelUtlik** [PavelUtlik/IT3kurs#6]
Графа "Дата окончания" имеет неудобный формат, поменять на ДД.ММ.ГГГГ

![image](https://user-images.githubusercontent.com/39675568/56870309-47ec3d00-6a16-11e9-9968-54f410ad4c2e.png)

**Comment by vliplianina** [comment]
Дубликат issue #5 Найдите ещё один дефект или запрос на улучшение.
Например, обратите внимание на кнопки "Сохранить" и "Отменить"
